name       : goocanvas1
version    : 1.0.0
release    : 3
source     :
    - https://download.gnome.org/sources/goocanvas/1.0/goocanvas-1.0.0.tar.bz2 : 1c072ef88567cad241fb4addee26e9bd96741b1503ff736d1c152fa6d865711e
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : GTK+2 Canvas Widget
description: |
    GooCanvas is a canvas widget for GTK+ that uses the cairo 2D library for drawing.
builddeps  :
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
